from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
import io
from datetime import datetime

def generate_pdf_report(check_result: dict, filename: str = "report.pdf") -> bytes:
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter
    
    # Header
    c.setFillColor(colors.darkblue)
    c.setFont("Helvetica-Bold", 24)
    c.drawString(50, height - 50, "LoanShield Due Diligence Report")
    
    c.setFillColor(colors.black)
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 80, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    c.drawString(50, height - 100, f"Loan ID: {check_result.get('loan_id', 'N/A')}")
    
    # Status Badge
    status = check_result.get('overall_status', 'UNKNOWN')
    c.setFont("Helvetica-Bold", 16)
    if status == "GREEN":
        c.setFillColor(colors.green)
    elif status == "AMBER":
        c.setFillColor(colors.orange)
    else:
        c.setFillColor(colors.red)
    c.drawString(50, height - 140, f"OVERALL STATUS: {status}")
    
    # Details
    c.setFillColor(colors.black)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 180, "Check Results:")
    
    y = height - 210
    c.setFont("Helvetica", 12)
    
    # Sanctions
    s_res = check_result.get('sanctions', {})
    c.drawString(70, y, f"Sanctions Check: {s_res.get('status')} - {s_res.get('details')}")
    y -= 30
    
    # Corporate
    c_res = check_result.get('corporate', {})
    c.drawString(70, y, f"Corporate Registry: {c_res.get('status')} - Active: {c_res.get('active')}")
    y -= 30
    
    # Credit
    cr_res = check_result.get('credit', {})
    c.drawString(70, y, f"Credit Rating: {cr_res.get('rating')} ({cr_res.get('score')} - {cr_res.get('status')})")
    
    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.setFillColor(colors.gray)
    c.drawString(50, 50, "Generated by LoanShield Automated Due Diligence System")
    
    c.showPage()
    c.save()
    
    buffer.seek(0)
    return buffer.getvalue()
